from typing import Any

DEFAULT_IMAGE_STYLES: list[dict[str, Any]] = [
    {
        "id": "dark-fantasy-painting",
        "name": "Dark Fantasy Painting",
        "description": "Moody brushwork with dramatic contrast and medieval grit.",
        "instruction": "dark fantasy painting, dramatic chiaroscuro, textured brush strokes, rich atmosphere",
        "image_url": "/assets/catalog/styles/dark-fantasy-painting_35657e9e.jpg",
    },
    {
        "id": "cinematic-realism",
        "name": "Cinematic Realism",
        "description": "Film-like composition with realistic lighting and depth.",
        "instruction": "cinematic realism, volumetric lighting, detailed environment, film still composition",
        "image_url": "/assets/catalog/styles/cinematic-realism_bd485f41.jpg",
    },
    {
        "id": "stylized-rpg-art",
        "name": "Stylized RPG Art",
        "description": "Bold outlines, vivid palettes, and heroic fantasy readability.",
        "instruction": "stylized RPG concept art, clean silhouettes, vibrant but grounded colors",
        "image_url": "/assets/catalog/styles/stylized-rpg-art_db5e95d6.jpg",
    },
    {
        "id": "grimdark-ink-sketch",
        "name": "Grimdark Ink Sketch",
        "description": "Raw, hand-drawn aesthetic with heavy ink washes and scratched textures.",
        "instruction": "grimdark ink sketch, cross-hatching, distressed paper texture, high contrast black and white",
        "image_url": "/assets/catalog/styles/grimdark-ink-sketch_023b9ad4.jpg",
    },
    {
        "id": "cyberpunk-neon",
        "name": "Cyberpunk Neon",
        "description": "Vibrant neon lights, rainy cityscapes, and high-tech grit.",
        "instruction": "cyberpunk aesthetic, synthwave colors, neon glow, wet asphalt reflections, futuristic noir",
        "image_url": "/assets/catalog/styles/cyberpunk-neon_e4b9fd38.jpg",
    },
    {
        "id": "ethereal-watercolor",
        "name": "Ethereal Watercolor",
        "description": "Soft, bleeding colors with a dreamlike, mystical atmosphere.",
        "instruction": "ethereal watercolor painting, soft edges, bleeding pigments, mystical light, dreamy pastel tones",
        "image_url": "/assets/catalog/styles/ethereal-watercolor_963ce2cd.jpg",
    },
    {
        "id": "science-fiction",
        "name": "Science-Fiction",
        "description": "Futuristic tech, vast space, and advanced starships.",
        "instruction": "futuristic science fiction world, starships in the sky, sleek high tech architecture, glowing neon lights, cinematic composition",
        "image_url": "/assets/catalog/styles/science-fiction_93659096.jpg",
    },
    {
        "id": "pixelart",
        "name": "Pixelart",
        "description": "Classic 90s adventure style with vibrant colors and charming pixels.",
        "instruction": "90s point and click adventure game pixel art, LucasArts style, vibrant limited color palette, pixelated aesthetic",
        "image_url": "/assets/catalog/styles/pixelart_5fb230a4.jpg",
    },
    {
        "id": "film-noir",
        "name": "Film Noir",
        "description": "Dramatic high-contrast black and white with long shadows and rainy streets.",
        "instruction": "Classic film noir, high contrast black and white, hard shadows, chiaroscuro lighting, rainy urban streets, Venetian blind shadows, 1940s cinematic aesthetic, grainy film texture.",
        "image_url": "/assets/catalog/styles/classic-film-noir_73cadd52.jpg",
    },
    {
        "id": "ghibli-whimsy",
        "name": "Ghibli-esque Whimsy",
        "description": "Soft, hand-painted anime aesthetics with lush nature and nostalgic lighting.",
        "instruction": "Studio Ghibli style, hand-painted aesthetic, lush green nature, soft morning light, vibrant but gentle colors, whimsical atmosphere, highly detailed background art.",
        "image_url": "/assets/catalog/styles/ghibli-esque-whimsy_37636857.jpg",
    },
    {
        "id": "retro-synthwave",
        "name": "Retro Synthwave",
        "description": "80s retro-futurism with glowing neon, wireframe grids, and vibrant purple tones.",
        "instruction": "Synthwave aesthetic, 1980s retro-futurism, neon pink and electric blue palette, glowing grid floor, retro sun, digital glitch effects, vibrant cyber-dream.",
        "image_url": "/assets/catalog/styles/retro-synthwave_47522b15.jpg",
    },
    {
        "id": "bio-organic-gothic",
        "name": "Bio-Organic Gothic",
        "description": "Eerie fusion of biology and machinery with dark metallic and skeletal details.",
        "instruction": "Bio-organic gothic, xenomorphic architecture, fused bone and cold metal, dark monochrome with slime highlights, eerie atmosphere, intricate mechanical biological details.",
        "image_url": "/assets/catalog/styles/bio-organic-gothic_23707b39.jpg",
    },
    {
        "id": "impressionist-oil",
        "name": "Impressionist Oil",
        "description": "Expressive oil painting with thick impasto strokes and vibrant light play.",
        "instruction": "Impressionist oil painting, thick impasto texture, visible palette knife strokes, vibrant color dabs, expressive light and shadow, romanticized atmosphere, canvas texture.",
        "image_url": "/assets/catalog/styles/impressionist-oil_801143d7.jpg",
    },
    {
        "id": "shonen-anime",
        "name": "Modern Shonen Anime",
        "description": "Sharp lines, dynamic digital lighting, and high-energy animation style.",
        "instruction": "Modern shonen anime style, crisp line art, dynamic cinematic lighting, vibrant cel-shading, high-octane energy, digital animation aesthetic, sharp focus, vivid special effects.",
        "image_url": "/assets/catalog/styles/modern-shonen-anime_7417820f.jpg",
    },
    {
        "id": "classical-heroic-comic",
        "name": "Classical Comic",
        "description": "Bold outlines, dynamic Ben-Day dots, and vibrant primary colors typical of classic Silver Age comics.",
        "instruction": "Classical comic book style, bold black ink outlines, Ben-Day dot shading, vibrant primary color palette, dynamic action composition, Silver Age comic aesthetic, dramatic shadows.",
        "image_url": "/assets/catalog/styles/classical-heroic-comic_8970c6ab.jpg",
    },
]

DEFAULT_TONES: list[dict[str, Any]] = [
    {
        "id": "horror",
        "name": "Horror",
        "description": "Dread, uncertainty, and escalating psychological pressure.",
        "instruction": "Maintain unsettling tension, sparse comfort, and consequences that feel dangerous.",
        "image_url": "/assets/catalog/tones/horror_7e4a6db5.jpg",
    },
    {
        "id": "sci-fi",
        "name": "Sci-Fi",
        "description": "Futuristic systems, unknown tech, and speculative mystery.",
        "instruction": "Use futuristic world logic, technical flavor, and discovery-driven narrative beats.",
        "image_url": "/assets/catalog/tones/sci-fi_0b2e548f.jpg",
    },
    {
        "id": "sitcom",
        "name": "Sitcom",
        "description": "Comedic misunderstandings, playful pacing, and memorable banter.",
        "instruction": "Favor witty dialogue, comic timing, and low-stakes chaos with charming setbacks.",
        "image_url": "/assets/catalog/tones/sitcom_3b747e63.jpg",
    },
    {
        "id": "classic-rpg",
        "name": "Classic RPG",
        "description": "Heroic quest tone with balanced drama and wonder.",
        "instruction": "Keep a classic heroic arc, meaningful choices, and clear quest momentum.",
        "image_url": "/assets/catalog/tones/classic-rpg_551efe58.jpg",
    },
    {
        "id": "heroic-epic",
        "name": "Heroic & Epic",
        "description": "Grand scale, legendary deeds, and inspiring bravery.",
        "instruction": "The tone is heroic and epic. Focus on grand scale, legendary atmosphere, and inspiring narratives.",
        "image_url": "/assets/catalog/tones/heroic-epic_9206142b.jpg",
    },
    {
        "id": "melancholic-somber",
        "name": "Melancholic & Somber",
        "description": "Reflective, sad, and focused on loss or faded glory.",
        "instruction": "The tone is melancholic and somber. Use reflective language, focus on themes of loss and beauty in sadness.",
        "image_url": "/assets/catalog/tones/melancholic-somber_e5a53a82.jpg",
    },
    {
        "id": "post-apocalyptic",
        "name": "Post-Apocalyptic Despair",
        "description": "Bleak survival and haunting memories of a lost world.",
        "instruction": "The tone is post-apocalyptic and bleak. Focus on the struggle for survival, scarcity of resources, faded glory of the old world, and the harsh, unforgiving reality of the present.",
        "image_url": "/assets/catalog/tones/post-apocalyptic-despair_cef1270d.jpg",
    },
    {
        "id": "cozy-whimsy",
        "name": "Cozy & Whimsical",
        "description": "Lighthearted magical wonder and warmth of companionship.",
        "instruction": "Maintain a cozy and whimsical tone. Focus on magical wonder, gentle humor, low-stakes conflict, and the heartwarming aspects of exploration and companionship.",
        "image_url": "/assets/catalog/tones/cozy-whimsical_5c43d53c.jpg",
    },
    {
        "id": "political-intrigue",
        "name": "Political Intrigue",
        "description": "Hidden agendas, power plays, and dangerous diplomacy.",
        "instruction": "The tone is one of political intrigue and social complexity. Focus on hidden agendas, subtle power plays, high-stakes diplomacy, and the tension of keeping secrets in a world of lies.",
        "image_url": "/assets/catalog/tones/political-intrigue_2396d222.jpg",
    },
    {
        "id": "cosmic-horror",
        "name": "Cosmic Horror",
        "description": "Existential dread and incomprehensible ancient mysteries.",
        "instruction": "Invoke a sense of cosmic horror. Focus on existential dread, incomprehensible ancient forces, the fragility of the human mind, and mysteries that are better left unsolved.",
        "image_url": "/assets/catalog/tones/cosmic-horror_8e1a9584.jpg",
    },
    {
        "id": "noir-detective",
        "name": "Noir Detective",
        "description": "Analytical crime solving and gritty moral ambiguity.",
        "instruction": "Adopt a noir detective tone. Focus on analytical observation, the search for clues, gritty underworld atmosphere, and the moral ambiguity of justice and crime.",
        "image_url": "/assets/catalog/tones/noir-detective-crime_16d8363f.jpg",
    },
    {
        "id": "absurd-slapstick",
        "name": "Absurd Slapstick",
        "description": "Ridiculous physical comedy and deadpan nonsensical reactions.",
        "instruction": "The tone is absurd slapstick. Use deadpan humor, emphasize ridiculous physical comedy, nonsensical dialogue, and over-the-top reactions. Serious situations should be undermined by absurdity and bizarre coincidences.",
        "image_url": "/assets/catalog/tones/absurd-slapstick_42e21daa.jpg",
    },
]
