class GenerationSayings:
    SAYINGS = [
        "Weaving the fabric of time...",
        "Laying the narrative bricks...",
        "Summoning the lore master...",
        "Untangling plot threads...",
        "Brewing dramatic tension...",
        "Polishing the plot twists...",
        "Calibrating the moral compass...",
        "Consulting the oracle...",
        "Rolling for initiative...",
        "Spawning existential dread...",
        "Manifesting destiny...",
        "Sprinkling plot armor...",
        "Bribing the dice gods...",
        "Aligning the cosmic narrative...",
        "Loading questionable life choices...",
        "Generating witty banter...",
        "Forging epic loot...",
        "Planting Chekhov's guns...",
        "Feeding the plot holes...",
        "Constructing elaborate backstories...",
        "Tuning the suspension of disbelief...",
        "Gathering the narrative fluff...",
        "Awakening dormant subplots...",
        "Distilling pure character motivation...",
        "Simulating dramatic pauses...",
        "Encrypting ancient secrets...",
        "Rendering atmospheric fog...",
        "Populating the rogue's gallery...",
        "Calculating the odds of survival...",
        "Infusing maximum angst...",
        "Assembling the McGuffin...",
        "Choreographing the final showdown...",
        "Sanding down the rough edges of reality...",
        "Hiding the Easter eggs...",
        "Drafting the villain's monologue...",
        "Stocking the local tavern...",
        "Checking for narrative consistency... (just kidding)",
        "Unleashing the plot hounds...",
        "Stretching the limits of credibility...",
        "Foreshadowing impending doom...",
        "Generating random encounters...",
        "Optimizing the hero's journey...",
        "Compiling the ancient prophecies...",
        "Debugging the magic system...",
        "Translating forgotten languages...",
        "Preparing the deus ex machina...",
        "Adjusting the dramatic irony...",
        "Crafting emotional baggage...",
        "Initializing the call to adventure...",
        "Downloading common sense (Error 404)...",
        "Resurrecting deleted scenes...",
        "Bargaining with the narrator...",
        "Quantifying the power of friendship...",
        "Inflating the villain's ego...",
        "Spilling ink on the spacetime continuum...",
        "Herding the background characters...",
        "Sharpening the cliffhangers...",
        "Concocting questionable potions...",
        "Dusting off the ancient tomes...",
        "Applying dramatic filters...",
        "Calculating the velocity of an unladen swallow...",
        "Rehearsing the bard's terrible songs...",
        "Placing the mimic in a totally obvious spot...",
        "Fleshing out the red herrings...",
        "Hiring extra goblin extras...",
        "Ensuring the tavern is adequately sketchy...",
        "Knitting the fabric of reality...",
        "Summoning an unnecessary plot twist...",
        "Rolling a nat 20 on worldbuilding...",
        "Bribing the local guards...",
        "Generating arbitrary lore dumps...",
        "Concealing the invisible walls...",
        "Testing the structural integrity of the fourth wall...",
        "Stocking the dungeons with questionable loot...",
        "Filing paperwork for the magic system...",
        "Re-routing the hero's journey...",
        "Waking up the sleeping dragons...",
        "Polishing the MacGuffin until it shines...",
        "Sprinkling in some existential crisis...",
        "Balancing the karma scales...",
        "Writing checks the plot can't cash...",
        "Untangling the spaghetti code of destiny...",
        "Pre-heating the volcano lair...",
        "Oiling the trapdoors...",
        "Planting the seeds of betrayal...",
        "Consulting the alignments chart...",
        "Tuning the boss battle music...",
        "Patching reality leaks...",
        "Casting 'Summon Narrative Cohesion'...",
        "Inventing words for the fantasy lexicon...",
        "Assigning tragic backstories...",
        "Waiting for the wizard (who is never late)...",
        "Sweeping the dungeon floors...",
        "Over-complicating the puzzle locks...",
        "Charging the crystal ball...",
        "Checking the hero's inventory capacity...",
        "Spraying anti-cliché repellent...",
        "Loading the 'happily ever after' contingency...",
        "Convincing the NPCs they have free will...",
        "Measuring the depth of the rabbit hole...",
        "Brewing a fresh pot of suspension of disbelief...",
        "Teaching the NPCs basic manners...",
        "Hiding the quest markers...",
        "Rolling a stealth check against the firewall...",
        "Inflating the local economy...",
        "Polishing the protagonist's tragic backstory...",
        "Sharpening the dialogue choices...",
        "Calibrating the morality slider...",
        "Bribing the random number generator...",
        "Ironing out the plot wrinkles...",
        "Ensuring the dog can be petted...",
        "Casting un-delete on the protagonist...",
        "Tuning the atmospheric dread...",
        "Watering the World Tree...",
        "Feeding the server gremlins...",
        "Checking the alignment of the stars...",
        "Consulting the Eldritch horrors...",
        "Translating goblin slang...",
        "Falsifying historical records...",
        "Generating tragic romances...",
        "Spawning exactly one (1) mimic...",
        "Hiding the good loot...",
        "Recalibrating the chosen one prophecy...",
        "Upgrading the peasant's pitchforks...",
        "Teaching the AI how to feel...",
        "Downloading epic background music...",
        "Drafting the sequel...",
        "Wrangling the plot bunnies...",
        "Inflating the final boss's HP...",
        "Applying mood lighting...",
        "Paving the road to good intentions...",
        "Calculating the terminal velocity of a gnome...",
        "Fleshing out the evil monologue...",
        "Giving the merchant a ridiculous accent...",
        "Rerolling the villain's stats...",
        "Smuggling contraband into the inventory...",
        "Paying off the narrator's gambling debts...",
        "Synchronizing the timeline...",
        "Summoning a bigger boat...",
        "Negotiating peace between plot points...",
        "Flipping the table and starting over...",
        "Adding completely unnecessary lore...",
        "Taming the wild side quests...",
        "Designing an overly complex lock mechanism...",
        "Distributing trauma equally among the party...",
        "Baking sweetrolls for theft...",
        "Polishing the hero's jawline...",
        "Setting up the inevitable betrayal...",
        "Rolling an insight check on the player...",
        "Forging documents of questionable authenticity...",
        "Preparing the 'Game Over' screen just in case...",
        "Hiding the fast travel points...",
        "Teaching the dragons how to breathe fire...",
        "Stocking the apothecary with dubious herbs...",
        "Washing the bloodstains off the armor...",
        "Calibrating the chaos engine...",
        "Summoning a mildly inconvenient storm...",
        "Pre-loading regret...",
        "Burying the treasure...",
        "Drawing the treasure map...",
        "Tearing the treasure map into four pieces...",
        "Giving the wise old mentor a persistent cough...",
        "Validating the laws of physics...",
        "Prompting the inner monologue...",
        "Lighting the torches in ancient, sealed ruins...",
        "Replacing the health potions with red food coloring...",
        "Checking for mimetic hazards...",
        "Deploying tactical plot twists...",
        "Armoring the bikini...",
        "Recharging the mana crystals...",
        "Telling the guards about an arrow to the knee...",
        "Hiding the key at the bottom of the lake...",
        "Spreading rumors in the local tavern...",
        "Teaching the skeletons how to dance...",
        "Making the puzzle solution painfully obvious...",
        "Delaying the inevitable...",
        "Filing the villain's taxes...",
        "Planting the magic beans...",
        "Casting 'Detect Magic' on the database...",
        "Summoning the ghost in the machine...",
        "Writing a heavily biased history book...",
        "Constructing a labyrinth without an exit...",
        "Distributing legendary items to level 1 rats...",
        "Ensuring the bridge troll has a valid riddle...",
        "Calibrating the emotional damage...",
        "Rolling the dice of destiny...",
        "Pre-rendering the dramatic rain...",
        "Applying rust to the iron gates...",
        "Teaching the parrots cryptic phrases...",
        "Balancing the encounter difficulty...",
        "Unbalancing the encounter difficulty...",
        "Hiring a necromancer for IT support...",
        "Loading an absurd amount of cheese...",
        "Dusting the cobwebs...",
        "Placing cobwebs where you just dusted...",
        "Fomenting a peasant rebellion...",
        "Adding spikes to the villain's armor...",
        "Tuning the squeak of the tavern sign...",
        "Ensuring at least one NPC is incredibly annoying...",
        "Generating a very specific prophecy...",
        "Misinterpreting the ancient texts...",
        "Tuning the acoustic properties of the dungeon...",
        "Scattering mysterious journals around...",
        "Reticulating splines...",
        "Generating terrain... wait, wrong genre...",
        "Hand-crafting artisan dialogue trees...",
        "Failing a charisma check with the server...",
        "Casting 'Mending' on broken code...",
        "Summoning a flock of ominous ravens...",
        "Bribing the ferryman...",
        "Tying the damsel to the train tracks...",
        "Realizing trains don't exist yet, untying damsel...",
        "Tying the damsel to the dragon tracks...",
        "Enchanting the loading bar...",
        "Feeding the gelatinous cube...",
        "Casting 'Prestidigitation' on the UI...",
        "Smuggling potions past customs...",
        "Prolonging the inevitable...",
        "Stakes: Raised.",
        "Foreshadowing the foreshadowing...",
        "Min-maxing the villain...",
        "Hiding the quicksave button...",
        "Polishing the dialogue trees...",
        "Arguing with the algorithm...",
        "Translating from Elvish...",
        "Siphoning magic from the ley lines...",
        "Organizing the inventory alphabetically...",
        "Searching for the 'Any' key...",
        "Calibrating the sarcasm detectors...",
        "Loading the concept of time...",
        "Checking if the coast is clear...",
        "Spawning a suspicious barrel...",
        "Designing a terribly impractical sword...",
        "Calculating the exact weight of a soul...",
        "Sprinkling fairy dust on the servers...",
        "Updating the grimoire...",
        "Tuning the ominous chanting...",
        "Hiding the plot armor in the laundry...",
        "Feeding the plot bunnies...",
        "Casting a spell of minor distraction...",
        "Ensuring the cape flutters dramatically...",
        "Re-evaluating life choices...",
        "Rolling a nat 1 on perception...",
        "Consulting the big book of clichés...",
        "Installing the false sense of security...",
        "Releasing the kraken...",
        "Realizing we don't have a kraken budget...",
        "Releasing a moderately angry squid...",
        "Polishing the brass fittings of steampunk airships...",
        "Encrypting the elder scrolls...",
        "Tuning the frequency of random encounters...",
        "Loading unresolved childhood trauma...",
        "Gathering the party before venturing forth...",
        "Filing a complaint with the Guild of Mages...",
        "Checking the expiration date on health potions...",
        "Summoning a dramatic gust of wind...",
        "Making the antagonist surprisingly sympathetic...",
        "Adding a completely unnecessary romance subplot...",
        "Deleting the fourth wall...",
        "Upgrading the graphics in your imagination...",
        "Buffing the final boss...",
        "Nerfing the player's favorite weapon...",
        "Checking the structural integrity of the plot...",
        "Washing the protagonist's one outfit...",
        "Planting the sword in the stone...",
        "Supergluing the sword in the stone...",
        "Loading the burden of glorious purpose...",
        "Tuning the echo in the cavern...",
        "Teaching the bandits a new catchphrase...",
        "Rehearsing the villain's tragic backstory...",
        "Spawning infinite rats in the cellar...",
        "Generating a very convenient coincidence...",
        "Casting 'Silence' on the peanut gallery...",
        "Loading the inevitable sequel hook...",
        "Making sure the math ain't mathing...",
        "Waking the ancient slumbering evil...",
        "Hitting snooze on the ancient slumbering evil...",
        "Brewing the elixir of life...",
        "Finding a really cool stick...",
        "Making the shadows 20% spookier...",
        "Adding a mysterious hooded figure to the corner...",
        "Tuning the crickets for awkward silences...",
    ]
