"""update style tone storage

Revision ID: 1fa8596cf725
Revises: df909b39afb3
Create Date: 2026-05-04 17:13:43.048644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1fa8596cf725'
down_revision: Union[str, Sequence[str], None] = 'df909b39afb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('selected_tone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('selected_tone',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
