"""add_dynamic_constraints

Revision ID: 1fda10c6f25c
Revises: 6012a4a035de
Create Date: 2026-05-23 23:14:33.482904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1fda10c6f25c'
down_revision: Union[str, Sequence[str], None] = '6012a4a035de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_containers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_items', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_items', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('text_log_generation_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('min_text_logs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_text_logs', sa.Integer(), nullable=True))
        batch_op.alter_column('min_scenes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_scenes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_containers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'8'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('max_containers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'8'"))
        batch_op.alter_column('max_scenes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_scenes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('max_text_logs')
        batch_op.drop_column('min_text_logs')
        batch_op.drop_column('text_log_generation_enabled')
        batch_op.drop_column('max_items')
        batch_op.drop_column('min_items')
        batch_op.drop_column('min_containers')

    # ### end Alembic commands ###
