"""Add session_id to world_maps

Revision ID: 2ba136b02955
Revises: 8f7afab8a637
Create Date: 2026-05-11 22:50:22.603019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2ba136b02955'
down_revision: Union[str, Sequence[str], None] = '8f7afab8a637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_world_maps_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_world_maps_session_id', 'game_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_world_maps_session_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_world_maps_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('is_ready',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
