"""add copied_from_id to game_sessions

Revision ID: 30b3bd896258
Revises: a9d4c1b2e7f0
Create Date: 2026-05-19 18:57:46.640084
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '30b3bd896258'
down_revision: Union[str, Sequence[str], None] = 'a9d4c1b2e7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copied_from_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_sessions_copied_from_id_game_sessions'), 'game_sessions', ['copied_from_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_world_maps_template_id_adventure_templates'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_world_maps_template_id_adventure_templates'), 'adventure_templates', ['template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_world_maps_template_id_adventure_templates'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_world_maps_template_id_adventure_templates'), 'adventure_templates', ['template_id'], ['id'])

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_sessions_copied_from_id_game_sessions'), type_='foreignkey')
        batch_op.drop_column('copied_from_id')

    # ### end Alembic commands ###
