"""add_reveal_rule_to_world_entities

Revision ID: 373783a380c1
Revises: a9d4c1b2e7f0
Create Date: 2026-05-20 09:47:23.650210
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '373783a380c1'
down_revision: Union[str, Sequence[str], None] = 'a9d4c1b2e7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reveal_rule', sa.String(length=500), nullable=True))

    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_world_maps_template_id_adventure_templates'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_world_maps_template_id_adventure_templates'), 'adventure_templates', ['template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_maps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_world_maps_template_id_adventure_templates'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_world_maps_template_id_adventure_templates'), 'adventure_templates', ['template_id'], ['id'])

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_column('reveal_rule')

    # ### end Alembic commands ###
