"""Add core RPG stats to Avatar and Character

Revision ID: 6102c29e351b
Revises: d2f4a1b9c8e7
Create Date: 2026-04-17 20:17:45.148766
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6102c29e351b'
down_revision: Union[str, Sequence[str], None] = 'd2f4a1b9c8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=False, server_default='10'))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('movement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('npc_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tone_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image_styles_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('armor_class')
        batch_op.drop_column('charisma')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('strength')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('armor_class')
        batch_op.drop_column('charisma')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('strength')

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('quests',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_tone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_image_styles',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rule_enforcement_mode',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'strict'"))

    # ### end Alembic commands ###
