"""Add min_scenes and max_scenes to Adventure

Revision ID: 6ce941dd2d33
Revises: 6102c29e351b
Create Date: 2026-04-17 21:25:56.525443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = '6ce941dd2d33'
down_revision: Union[str, Sequence[str], None] = '6102c29e351b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_adventures')
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('rule_enforcement_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'strict'"))
        batch_op.alter_column('selected_image_styles',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('selected_tone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('quests',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_styles_catalog',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tone_catalog',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('npc_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('movement_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_scenes', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('max_scenes', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('movement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('npc_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tone_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image_styles_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('quests',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_tone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_image_styles',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rule_enforcement_mode',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'strict'"))
        batch_op.drop_column('max_scenes')
        batch_op.drop_column('min_scenes')

    op.create_table('_alembic_tmp_adventures',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('strict_rules', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('heartbeat_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('game_over_rules', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('context', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('time_per_turn', sa.INTEGER(), nullable=False),
    sa.Column('original_manifest', sqlite.JSON(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('creation_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('creation_error', sa.VARCHAR(length=500), nullable=True),
    sa.Column('heartbeat_interval', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('rule_enforcement_mode', sa.VARCHAR(length=16), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sqlite.JSON(), nullable=True),
    sa.Column('selected_tone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('quests', sqlite.JSON(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
