"""Add min_scenes and max_scenes to Adventure

Revision ID: 6ce941dd2d33
Revises: 6102c29e351b
Create Date: 2026-04-17 21:25:56.525443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = '6ce941dd2d33'
down_revision: Union[str, Sequence[str], None] = '6102c29e351b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    adventure_cols = {c["name"] for c in inspector.get_columns("adventures")} if "adventures" in tables else set()
    user_cols = {c["name"] for c in inspector.get_columns("users")} if "users" in tables else set()
    world_entities_cols = {c["name"] for c in inspector.get_columns("world_entities")} if "world_entities" in tables else set()

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        # Handle rule_enforcement_mode
        if 'rule_enforcement_mode' in adventure_cols:
            batch_op.alter_column('rule_enforcement_mode',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=16),
                   existing_nullable=False,
                   existing_server_default=sa.text("'strict'"))
        else:
            batch_op.add_column(sa.Column('rule_enforcement_mode', sa.String(length=16), nullable=False, server_default=sa.text("'strict'")))

        # Handle selected_image_styles
        if 'selected_image_styles' in adventure_cols:
            batch_op.alter_column('selected_image_styles',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        else:
            batch_op.add_column(sa.Column('selected_image_styles', sa.JSON(), nullable=True))

        # Handle selected_tone
        if 'selected_tone' in adventure_cols:
            batch_op.alter_column('selected_tone',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=100),
                   existing_nullable=True)
        else:
            batch_op.add_column(sa.Column('selected_tone', sa.String(length=100), nullable=True))

        # Handle quests (The problematic one)
        if 'quests' in adventure_cols:
            batch_op.alter_column('quests',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        else:
            batch_op.add_column(sa.Column('quests', sa.JSON(), nullable=True))

        # Handle is_completed
        if 'is_completed' not in adventure_cols:
            batch_op.add_column(sa.Column('is_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

        # Handle min_scenes and max_scenes
        if 'min_scenes' not in adventure_cols:
            batch_op.add_column(sa.Column('min_scenes', sa.Integer(), nullable=False, server_default='1'))
        if 'max_scenes' not in adventure_cols:
            batch_op.add_column(sa.Column('max_scenes', sa.Integer(), nullable=False, server_default='5'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'image_styles_catalog' in user_cols:
            batch_op.alter_column('image_styles_catalog',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        if 'tone_catalog' in user_cols:
            batch_op.alter_column('tone_catalog',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        if 'npc_type' in world_entities_cols:
            batch_op.alter_column('npc_type',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=50),
                   existing_nullable=True)
        if 'movement_type' in world_entities_cols:
            batch_op.alter_column('movement_type',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=50),
                   existing_nullable=True)

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('movement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('npc_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tone_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image_styles_catalog',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('quests',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_tone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selected_image_styles',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rule_enforcement_mode',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'strict'"))
        batch_op.drop_column('max_scenes')
        batch_op.drop_column('min_scenes')

    # ### end Alembic commands ###
