"""new_game_turn_concept

Revision ID: 6dc8e0811c64
Revises: 68636ceb2b38
Create Date: 2026-04-30 09:51:57.178865
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6dc8e0811c64'
down_revision: Union[str, Sequence[str], None] = '68636ceb2b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('adventures')
    # op.drop_table('game_states')
    conn = op.get_bind()
    columns = [c['name'] for c in sa.inspect(conn).get_columns('adventure_templates')]
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        if 'plot' not in columns:
            batch_op.add_column(sa.Column('plot', sa.String(length=5000), nullable=True))
        if 'rules' not in columns:
            batch_op.add_column(sa.Column('rules', sa.String(length=5000), nullable=True))
        if 'walkthrough' not in columns:
            batch_op.add_column(sa.Column('walkthrough', sa.String(length=10000), nullable=True))
        if 'completed_condition' not in columns:
            batch_op.add_column(sa.Column('completed_condition', sa.String(length=1000), nullable=True))
        if 'gameover_condition' not in columns:
            batch_op.add_column(sa.Column('gameover_condition', sa.String(length=1000), nullable=True))
        if 'original_prompt' not in columns:
            batch_op.add_column(sa.Column('original_prompt', sa.String(length=5000), nullable=True))
        if 'starting_timestamp' not in columns:
            batch_op.add_column(sa.Column('starting_timestamp', sa.Integer(), server_default="0", nullable=False))

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        avatar_cols = [c['name'] for c in sa.inspect(conn).get_columns('avatars')]
        if 'adventure_id' in avatar_cols:
            batch_op.drop_column('adventure_id')

    with op.batch_alter_table('session_states', schema=None) as batch_op:
        ss_cols = [c['name'] for c in sa.inspect(conn).get_columns('session_states')]
        if 'plot' not in ss_cols:
            batch_op.add_column(sa.Column('plot', sa.String(length=5000), nullable=True))
        if 'rules' not in ss_cols:
            batch_op.add_column(sa.Column('rules', sa.String(length=5000), nullable=True))
        if 'walkthrough' not in ss_cols:
            batch_op.add_column(sa.Column('walkthrough', sa.String(length=10000), nullable=True))
        if 'completed_condition' not in ss_cols:
            batch_op.add_column(sa.Column('completed_condition', sa.String(length=1000), nullable=True))
        if 'gameover_condition' not in ss_cols:
            batch_op.add_column(sa.Column('gameover_condition', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        we_cols = [c['name'] for c in sa.inspect(conn).get_columns('world_entities')]
        if 'pk' not in we_cols:
            batch_op.add_column(sa.Column('pk', sa.Integer(), autoincrement=True, nullable=True))
        if 'session_id' not in we_cols:
            batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key('fk_world_entities_session_id', 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_world_entities_template_id', 'adventure_templates', ['template_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('world_exits', schema=None) as batch_op:
        wx_cols = [c['name'] for c in sa.inspect(conn).get_columns('world_exits')]
        if 'session_id' not in wx_cols:
            batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key('fk_world_exits_session_id', 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_world_exits_template_id', 'adventure_templates', ['template_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        ws_cols = [c['name'] for c in sa.inspect(conn).get_columns('world_scenes')]
        if 'pk' not in ws_cols:
            batch_op.add_column(sa.Column('pk', sa.Integer(), autoincrement=True, nullable=True))
        if 'session_id' not in ws_cols:
            batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key('fk_world_scenes_session_id', 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_world_scenes_template_id', 'adventure_templates', ['template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'adventure_templates', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('session_id')
        batch_op.drop_column('pk')

    with op.batch_alter_table('world_exits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'adventure_templates', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('session_id')

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'adventure_templates', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('template_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('session_id')
        batch_op.drop_column('pk')

    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.drop_column('gameover_condition')
        batch_op.drop_column('completed_condition')
        batch_op.drop_column('walkthrough')
        batch_op.drop_column('rules')
        batch_op.drop_column('plot')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adventure_id', sa.TEXT(), nullable=True))

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.drop_column('starting_timestamp')
        batch_op.drop_column('original_prompt')
        batch_op.drop_column('gameover_condition')
        batch_op.drop_column('completed_condition')
        batch_op.drop_column('walkthrough')
        batch_op.drop_column('rules')
        batch_op.drop_column('plot')

    op.create_table('game_states',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_debug_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventures',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('game_over_rules', sa.TEXT(), nullable=True),
    sa.Column('rule_enforcement_mode', sa.TEXT(), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sa.TEXT(), nullable=True),
    sa.Column('selected_tone', sa.TEXT(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creation_status', sa.TEXT(), nullable=True),
    sa.Column('creation_error', sa.TEXT(), nullable=True),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('quests', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('original_manifest', sa.TEXT(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
