"""Add advanced item management columns to world_entities

Revision ID: 6e9a80fa38b7
Revises: 70ac5db86575
Create Date: 2026-04-13 22:10:13.956557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6e9a80fa38b7'
down_revision: Union[str, Sequence[str], None] = '70ac5db86575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    adventure_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('adventures')")).fetchall()]
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        if 'heartbeat_interval' in adventure_cols:
            batch_op.drop_column('heartbeat_interval')

    world_entities_exists = conn.execute(
        sa.text("SELECT 1 FROM sqlite_master WHERE type='table' AND name='world_entities'")
    ).fetchone() is not None
    if world_entities_exists:
        world_entity_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('world_entities')")).fetchall()]
        with op.batch_alter_table('world_entities', schema=None) as batch_op:
            if 'item_type' not in world_entity_cols:
                batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=True))
            if 'wearable_slots' not in world_entity_cols:
                batch_op.add_column(sa.Column('wearable_slots', sa.JSON(), nullable=True))
            if 'is_in_inventory' not in world_entity_cols:
                batch_op.add_column(sa.Column('is_in_inventory', sa.Boolean(), server_default=sa.text('0'), nullable=False))
            if 'is_hidden' not in world_entity_cols:
                batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('is_in_inventory')
        batch_op.drop_column('wearable_slots')
        batch_op.drop_column('item_type')

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_interval', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False))

    # ### end Alembic commands ###
