"""Add advanced item management columns to world_entities

Revision ID: 6e9a80fa38b7
Revises: 70ac5db86575
Create Date: 2026-04-13 22:10:13.956557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6e9a80fa38b7'
down_revision: Union[str, Sequence[str], None] = '70ac5db86575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_interval')

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wearable_slots', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_in_inventory', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('is_in_inventory')
        batch_op.drop_column('wearable_slots')
        batch_op.drop_column('item_type')

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_interval', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False))

    # ### end Alembic commands ###
