"""Add auth

Revision ID: 7025638c1ac2
Revises: 6ce941dd2d33
Create Date: 2026-04-22 10:10:09.769847
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7025638c1ac2'
down_revision: Union[str, Sequence[str], None] = '6ce941dd2d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default="user"))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.drop_index(batch_op.f('uq_users_username'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_users_username'), ['username'], unique=1)
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('role')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
