"""Add auth

Revision ID: 7025638c1ac2
Revises: 6ce941dd2d33
Create Date: 2026-04-22 10:10:09.769847
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7025638c1ac2'
down_revision: Union[str, Sequence[str], None] = '6ce941dd2d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(bind, table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(column['name'] == column_name for column in inspector.get_columns(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    with op.batch_alter_table('users', schema=None) as batch_op:
        if not _has_column(bind, 'users', 'hashed_password'):
            batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=""))
        if not _has_column(bind, 'users', 'role'):
            batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default="user"))
        if not _has_column(bind, 'users', 'profile_image_url'):
            batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))
        if not _has_column(bind, 'users', 'bio'):
            batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    with op.batch_alter_table('users', schema=None) as batch_op:
        if _has_column(bind, 'users', 'bio'):
            batch_op.drop_column('bio')
        if _has_column(bind, 'users', 'profile_image_url'):
            batch_op.drop_column('profile_image_url')
        if _has_column(bind, 'users', 'role'):
            batch_op.drop_column('role')
        if _has_column(bind, 'users', 'hashed_password'):
            batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
