"""batch update adventure and character

Revision ID: 70ac5db86575
Revises: fed66755a227
Create Date: 2026-04-13 21:00:10.332519
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '70ac5db86575'
down_revision: Union[str, Sequence[str], None] = 'fed66755a227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Detect existing columns to handle older DB schemas gracefully
    conn = op.get_bind()
    existing_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('adventures')")).fetchall()]

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_per_turn', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('original_manifest', sa.JSON(), nullable=True))
        batch_op.alter_column(
            'title',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

        if 'is_ready' in existing_cols:
            batch_op.alter_column(
                'is_ready',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text('1'),
            )
        else:
            # If the column does not exist in older DBs, add it instead of failing
            batch_op.add_column(sa.Column('is_ready', sa.Boolean(), server_default=sa.text('1'), nullable=True))

        if 'creation_status' in existing_cols:
            batch_op.alter_column(
                'creation_status',
                existing_type=sa.TEXT(),
                type_=sa.String(length=100),
                existing_nullable=True,
            )
        else:
            batch_op.add_column(sa.Column('creation_status', sa.String(length=100), nullable=True))

        if 'creation_error' in existing_cols:
            batch_op.alter_column(
                'creation_error',
                existing_type=sa.TEXT(),
                type_=sa.String(length=500),
                existing_nullable=True,
            )
        else:
            batch_op.add_column(sa.Column('creation_error', sa.String(length=500), nullable=True))

        if 'heartbeat_interval' in existing_cols:
            batch_op.drop_column('heartbeat_interval')

    # Handle avatars table changes safely for older DBs
    avatars_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('avatars')")).fetchall()]
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        if 'adventure_id' in avatars_cols:
            batch_op.alter_column(
                'adventure_id',
                existing_type=sa.TEXT(),
                type_=sa.String(length=36),
                existing_nullable=True,
            )
        else:
            batch_op.add_column(sa.Column('adventure_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_avatars_adventure_id', 'adventures', ['adventure_id'], ['id'])

    # Handle users table changes safely for older DBs
    users_cols = [r[1] for r in conn.execute(sa.text("PRAGMA table_info('users')")).fetchall()]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'llm_settings' in users_cols:
            batch_op.alter_column('llm_settings', existing_type=sa.TEXT(), type_=sa.JSON(), existing_nullable=True)
        else:
            batch_op.add_column(sa.Column('llm_settings', sa.JSON(), nullable=True))

        if 't2i_settings' in users_cols:
            batch_op.alter_column('t2i_settings', existing_type=sa.TEXT(), type_=sa.JSON(), existing_nullable=True)
        else:
            batch_op.add_column(sa.Column('t2i_settings', sa.JSON(), nullable=True))

        # Recreate/rename username index/constraint safely
        try:
            batch_op.drop_index(batch_op.f('uq_users_username'))
        except Exception:
            pass
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_index(batch_op.f('uq_users_username'), ['username'], unique=1)
        batch_op.alter_column('t2i_settings', existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column('llm_settings', existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=True)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_avatars_adventure_id', type_='foreignkey')
        batch_op.alter_column('adventure_id', existing_type=sa.String(length=36), type_=sa.TEXT(), existing_nullable=True)

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_interval', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False))
        batch_op.alter_column('creation_error', existing_type=sa.String(length=500), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column('creation_status', existing_type=sa.String(length=100), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column('is_ready', existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text('1'))
        batch_op.alter_column('title', existing_type=sa.String(length=50), type_=sa.VARCHAR(length=255), existing_nullable=False)
        batch_op.drop_column('original_manifest')
        batch_op.drop_column('time_per_turn')

    # ### end Alembic commands ###
