"""Add script triggers to entities and scenes

Revision ID: 70c211b399de
Revises: 469bc262d980
Create Date: 2026-10-10 12:58:40.789008
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '70c211b399de'
down_revision: Union[str, Sequence[str], None] = '469bc262d980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_states')
    op.drop_table('adventures')
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('sequences',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('generation_strictness',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'creative'"))

    with op.batch_alter_table('ai_fix_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_fix_cache_user_template_finding'))
        batch_op.drop_constraint(batch_op.f('uq_ai_fix_cache_user_template_finding'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ai_fix_cache_finding_signature'), ['finding_signature'], unique=False)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('adventure_id')

    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.alter_column('walkthrough',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=20000),
               existing_nullable=True)
        batch_op.alter_column('active_sequence_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('save_on_scene_change')
        batch_op.drop_column('save_on_combat')
        batch_op.drop_column('turn_count')
        batch_op.drop_column('save_interval')

    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_template'))
        batch_op.drop_index(batch_op.f('ix_validation_runs_user'))
        batch_op.drop_index(batch_op.f('ix_validation_runs_user_template'))
        batch_op.create_index(batch_op.f('ix_validation_runs_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('world_exits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_open_exit_script', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('on_open_exit_text', sa.String(length=5000), nullable=True))

    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_enter_scene_script', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('on_enter_scene_text', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        batch_op.drop_column('on_enter_scene_text')
        batch_op.drop_column('on_enter_scene_script')

    with op.batch_alter_table('world_exits', schema=None) as batch_op:
        batch_op.drop_column('on_open_exit_text')
        batch_op.drop_column('on_open_exit_script')

    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_validation_runs_template_id'))
        batch_op.create_index(batch_op.f('ix_validation_runs_user_template'), ['user_id', 'template_id', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_runs_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_runs_template'), ['template_id'], unique=False)

    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_interval', sa.INTEGER(), server_default=sa.text("'5'"), nullable=False))
        batch_op.add_column(sa.Column('turn_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('save_on_combat', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('save_on_scene_change', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.alter_column('active_sequence_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('walkthrough',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adventure_id', sa.TEXT(), nullable=True))

    with op.batch_alter_table('ai_fix_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_fix_cache_finding_signature'))
        batch_op.create_unique_constraint(batch_op.f('uq_ai_fix_cache_user_template_finding'), ['template_id', 'user_id', 'finding_signature'])
        batch_op.create_index(batch_op.f('ix_ai_fix_cache_user_template_finding'), ['user_id', 'template_id', 'finding_signature'], unique=False)

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('generation_strictness',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'creative'"))
        batch_op.alter_column('sequences',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('adventures',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('game_over_rules', sa.TEXT(), nullable=True),
    sa.Column('rule_enforcement_mode', sa.TEXT(), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sa.TEXT(), nullable=True),
    sa.Column('selected_tone', sa.TEXT(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creation_status', sa.TEXT(), nullable=True),
    sa.Column('creation_error', sa.TEXT(), nullable=True),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('quests', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('original_manifest', sa.TEXT(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.Column('creator', sa.TEXT(), nullable=True),
    sa.Column('copyright', sa.TEXT(), nullable=True),
    sa.Column('license', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_states',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_debug_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
