"""add_world_memories_and_rumors

Revision ID: 764a99e41994
Revises: b3c4d5e6f7a8
Create Date: 2026-06-25 08:37:00.328644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '764a99e41994'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_memories', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('world_rumors', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.drop_column('world_rumors')
        batch_op.drop_column('world_memories')

    # ### end Alembic commands ###
