"""remove unique constraint from world_maps

Revision ID: 7ae7731acd3b
Revises: 2ba136b02955
Create Date: 2026-05-11 22:57:42.667452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae7731acd3b'
down_revision: Union[str, Sequence[str], None] = '2ba136b02955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update users (optional but good)
    try:
        with op.batch_alter_table('users', schema=None, naming_convention=naming_convention) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
    except Exception:
        pass

    # 2. Find the index name for the unique constraint on world_maps.template_id
    conn = op.get_bind()
    # Use PRAGMA to find the index name since it might be an auto-index
    res = conn.execute(sa.text("PRAGMA index_list('world_maps')")).fetchall()
    target_index = None
    for row in res:
        # row: (seq, name, unique, origin, partial)
        if row[2] == 1: # unique index
            info = conn.execute(sa.text(f"PRAGMA index_info('{row[1]}')")).fetchall()
            # info: (seqno, cid, name)
            for col in info:
                if col[2] == 'template_id':
                    target_index = row[1]
                    break
            if target_index:
                break
    
    if target_index:
        with op.batch_alter_table('world_maps', schema=None) as batch_op:
            # Drop the constraint by its discovered name
            batch_op.drop_constraint(target_index, type_='unique')
    else:
        # Fallback: try by convention just in case
        try:
            with op.batch_alter_table('world_maps', schema=None, naming_convention=naming_convention) as batch_op:
                batch_op.drop_constraint('uq_world_maps_template_id', type_='unique')
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_maps', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint('uq_world_maps_template_id', ['template_id'])

    try:
        with op.batch_alter_table('users', schema=None, naming_convention=naming_convention) as batch_op:
            batch_op.drop_constraint('uq_users_username', type_='unique')
    except Exception:
        pass
    # ### end Alembic commands ###
