"""remove unique constraint from world_maps

Revision ID: 7ae7731acd3b
Revises: 2ba136b02955
Create Date: 2026-05-11 22:57:42.667452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae7731acd3b'
down_revision: Union[str, Sequence[str], None] = '2ba136b02955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update users (optional but good)
    try:
        with op.batch_alter_table('users', schema=None, naming_convention=naming_convention) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
    except Exception:
        pass

    # 2. Find the index name for the unique constraint on world_maps.template_id
    conn = op.get_bind()
    
    # Use SQLAlchemy reflection to find the constraint name as it sees it
    from sqlalchemy.engine import reflection
    insp = reflection.Inspector.from_engine(conn)
    
    target_constraint = None
    
    # Check unique constraints first
    uqs = insp.get_unique_constraints('world_maps')
    for uq in uqs:
        if 'template_id' in uq['column_names']:
            target_constraint = uq['name']
            break
            
    if target_constraint:
        with op.batch_alter_table('world_maps', schema=None) as batch_op:
            batch_op.drop_constraint(target_constraint, type_='unique')
    else:
        # Check indexes if not found as a constraint (SQLite often treats them as indexes)
        idxs = insp.get_indexes('world_maps')
        for idx in idxs:
            if idx.get('unique') and 'template_id' in idx['column_names']:
                target_constraint = idx['name']
                break
        
        if target_constraint:
            with op.batch_alter_table('world_maps', schema=None) as batch_op:
                batch_op.drop_index(target_constraint)
        else:
            # Last resort: try by convention
            try:
                with op.batch_alter_table('world_maps', schema=None, naming_convention=naming_convention) as batch_op:
                    batch_op.drop_constraint('uq_world_maps_template_id', type_='unique')
            except Exception:
                pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_maps', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint('uq_world_maps_template_id', ['template_id'])

    try:
        with op.batch_alter_table('users', schema=None, naming_convention=naming_convention) as batch_op:
            batch_op.drop_constraint('uq_users_username', type_='unique')
    except Exception:
        pass
    # ### end Alembic commands ###
