"""add tts_settings to user

Revision ID: 886aaf16818a
Revises: dab2beb3a37f
Create Date: 2026-05-08 10:52:45.074146
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '886aaf16818a'
down_revision = 'dab2beb3a37f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('intro_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=20000),
               existing_nullable=True)
        batch_op.alter_column('walkthrough',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=20000),
               existing_nullable=True)
        batch_op.alter_column('completed_condition',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('gameover_condition',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('original_prompt',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=20000),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tts_settings')

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('original_prompt',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('gameover_condition',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('completed_condition',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('walkthrough',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('intro_text',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###
