"""add_bable_fish_languages

Revision ID: 8b868cca04d6
Revises: 43831f53a321
Create Date: 2026-05-01 22:13:24.264380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = '8b868cca04d6'
down_revision: Union[str, Sequence[str], None] = '43831f53a321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('game_states')
    # op.drop_table('adventures')
    # op.drop_table('_alembic_tmp_adventure_templates')
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.drop_column('context')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.alter_column('max_hp',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(200)'))
        batch_op.alter_column('max_stamina',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(200)'))
        batch_op.alter_column('max_mana',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(200)'))
        batch_op.drop_column('adventure_id')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('status_note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('game_log',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.add_column(sa.Column('default_language', sa.String(length=20), nullable=True))

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=True))

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_scenes', schema=None) as batch_op:
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_language')
        batch_op.alter_column('game_log',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('status_note',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adventure_id', sa.TEXT(), nullable=True))
        batch_op.alter_column('max_mana',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(200)'))
        batch_op.alter_column('max_stamina',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(200)'))
        batch_op.alter_column('max_hp',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(200)'))

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.VARCHAR(length=2000), nullable=True))

    op.create_table('_alembic_tmp_adventure_templates',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('teaser', sa.VARCHAR(length=300), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('strict_rules', sa.BOOLEAN(), nullable=False),
    sa.Column('rule_enforcement_mode', sa.VARCHAR(length=16), nullable=False),
    sa.Column('time_per_turn', sa.INTEGER(), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('generate_scene_images', sa.BOOLEAN(), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), nullable=False),
    sa.Column('selected_image_styles', sqlite.JSON(), nullable=True),
    sa.Column('selected_tone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('game_over_rules', sqlite.JSON(), nullable=True),
    sa.Column('quests', sqlite.JSON(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('is_ready', sa.BOOLEAN(), nullable=True),
    sa.Column('creation_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('creation_error', sa.VARCHAR(length=500), nullable=True),
    sa.Column('original_manifest', sqlite.JSON(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), nullable=False),
    sa.Column('awards', sqlite.JSON(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('plot', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('rules', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('walkthrough', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('completed_condition', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('gameover_condition', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('original_prompt', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('starting_timestamp', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('time_system', sa.VARCHAR(length=20), server_default=sa.text("'calendar'"), nullable=False),
    sa.Column('time_config', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventures',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('game_over_rules', sa.TEXT(), nullable=True),
    sa.Column('rule_enforcement_mode', sa.TEXT(), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sa.TEXT(), nullable=True),
    sa.Column('selected_tone', sa.TEXT(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creation_status', sa.TEXT(), nullable=True),
    sa.Column('creation_error', sa.TEXT(), nullable=True),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('quests', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('original_manifest', sa.TEXT(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_states',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_debug_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
