"""add tts_director_notes to session_state

Revision ID: 8f7afab8a637
Revises: d432fd0059f5
Create Date: 2026-05-10 01:58:19.055438
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f7afab8a637'
down_revision: str | Sequence[str] | None = 'd432fd0059f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_director_notes', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.drop_column('tts_director_notes')

    # ### end Alembic commands ###
