"""Add combination and portability columns to WorldEntity

Revision ID: aaf98fb37ad2
Revises: 6e9a80fa38b7
Create Date: 2026-04-14 21:47:24.947454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'aaf98fb37ad2'
down_revision: Union[str, Sequence[str], None] = '6e9a80fa38b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    avatar_cols = {r[1] for r in conn.execute(sa.text("PRAGMA table_info('avatars')")).fetchall()}
    world_entities_exists = conn.execute(
        sa.text("SELECT 1 FROM sqlite_master WHERE type='table' AND name='world_entities'")
    ).fetchone() is not None
    world_entity_cols = {r[1] for r in conn.execute(sa.text("PRAGMA table_info('world_entities')")).fetchall()} if world_entities_exists else set()

    if 'role' not in avatar_cols:
        op.add_column('avatars', sa.Column('role', sa.String(length=100), nullable=True))

    if 'description' not in avatar_cols:
        op.add_column('avatars', sa.Column('description', sa.String(length=1000), nullable=True))

    if 'profile_image' not in avatar_cols:
        op.add_column('avatars', sa.Column('profile_image', sa.String(length=255), nullable=True))

    if world_entities_exists:
        if 'is_portable' not in world_entity_cols:
            op.add_column('world_entities', sa.Column('is_portable', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        if 'combination_ingredients' not in world_entity_cols:
            op.add_column('world_entities', sa.Column('combination_ingredients', sa.JSON(), nullable=True))
        if 'reveals_item_id' not in world_entity_cols:
            op.add_column('world_entities', sa.Column('reveals_item_id', sa.String(length=50), nullable=True))
        if 'is_final_state' not in world_entity_cols:
            op.add_column('world_entities', sa.Column('is_final_state', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        if 'state_comment' not in world_entity_cols:
            op.add_column('world_entities', sa.Column('state_comment', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    world_entities_exists = conn.execute(
        sa.text("SELECT 1 FROM sqlite_master WHERE type='table' AND name='world_entities'")
    ).fetchone() is not None

    if world_entities_exists:
        with op.batch_alter_table('world_entities', schema=None) as batch_op:
            batch_op.drop_column('state_comment')
            batch_op.drop_column('is_final_state')
            batch_op.drop_column('reveals_item_id')
            batch_op.drop_column('combination_ingredients')
            batch_op.drop_column('is_portable')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
