"""Add is_attackable to world_entities

Revision ID: c75ba74ff965
Revises: 0b669575012e
Create Date: 2026-05-07 23:28:18.500049
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c75ba74ff965'
down_revision = '0b669575012e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_attackable', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_column('is_attackable')
    # ### end Alembic commands ###
