"""add tts_director_notes to adventure_template

Revision ID: d432fd0059f5
Revises: f3d9b0f2a1f4
Create Date: 2026-05-10 01:55:08.535778
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd432fd0059f5'
down_revision: str | Sequence[str] | None = 'f3d9b0f2a1f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_director_notes', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.drop_column('tts_director_notes')

    # ### end Alembic commands ###
