"""Add version column to adventure_templates

Revision ID: dab2beb3a37f
Revises: 0b669575012e
Create Date: 2026-05-08 07:18:01.726149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'dab2beb3a37f'
down_revision: Union[str, Sequence[str], None] = '0b669575012e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adventures')
    op.drop_table('game_states')
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=15), nullable=True))
        batch_op.alter_column('intro_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('adventure_id')

    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.alter_column('is_walkthrough_revealed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_states', schema=None) as batch_op:
        batch_op.alter_column('is_walkthrough_revealed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adventure_id', sa.TEXT(), nullable=True))

    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('intro_text',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('version')

    op.create_table('game_states',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_debug_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventures',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('game_over_rules', sa.TEXT(), nullable=True),
    sa.Column('rule_enforcement_mode', sa.TEXT(), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sa.TEXT(), nullable=True),
    sa.Column('selected_tone', sa.TEXT(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creation_status', sa.TEXT(), nullable=True),
    sa.Column('creation_error', sa.TEXT(), nullable=True),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('quests', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('original_manifest', sa.TEXT(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
