"""add generation_logs to adventure templates

Revision ID: e011bfa7b3fd
Revises: 60e5118dd305
Create Date: 2026-06-05 22:02:21.393429
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e011bfa7b3fd'
down_revision: Union[str, Sequence[str], None] = '60e5118dd305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_logs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.drop_column('generation_logs')

    # ### end Alembic commands ###
