"""add_quest_and_award_constraints

Revision ID: e3c88ba0e84a
Revises: 1fda10c6f25c
Create Date: 2026-05-23 23:25:03.596659
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e3c88ba0e84a'
down_revision: Union[str, Sequence[str], None] = '1fda10c6f25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quest_generation_enabled', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
        batch_op.add_column(sa.Column('min_quests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_quests', sa.Integer(), nullable=True))
        batch_op.alter_column('min_awards',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_awards',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('max_awards',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_awards',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('max_quests')
        batch_op.drop_column('min_quests')
        batch_op.drop_column('quest_generation_enabled')

    # ### end Alembic commands ###
