"""add owner_id to adventures

Revision ID: edffbdc72d01
Revises: 7025638c1ac2
Create Date: 2026-04-22 11:04:21.869441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'edffbdc72d01'
down_revision: Union[str, Sequence[str], None] = '7025638c1ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_adventure_owner', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.drop_constraint('fk_adventure_owner', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
