"""add npc goal and character

Revision ID: f5cd9e7c1c21
Revises: 7ae7731acd3b
Create Date: 2026-05-12 09:05:43.556121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f5cd9e7c1c21'
down_revision: Union[str, Sequence[str], None] = '7ae7731acd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('character', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world_entities', schema=None) as batch_op:
        batch_op.drop_column('character')
        batch_op.drop_column('goal')

    # ### end Alembic commands ###
