"""Add Character model and update Adventure

Revision ID: fed66755a227
Revises: 20260412_01
Create Date: 2026-04-13 10:56:21.148027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fed66755a227'
down_revision: Union[str, Sequence[str], None] = '20260412_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('status_effects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adventures', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('adventures', sa.Column('context', sa.String(length=2000), nullable=True))
    # op.alter_column('adventures', 'title',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    # op.drop_index(op.f('uq_users_username'), table_name='users')
    # op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('uq_users_username'), 'users', ['username'], unique=1)
    # op.alter_column('adventures', 'title',
    #            existing_type=sa.String(length=50),
    #            type_=sa.VARCHAR(length=255),
    #            existing_nullable=False)
    op.drop_column('adventures', 'context')
    op.drop_column('adventures', 'image_url')
    op.drop_table('characters')
    # ### end Alembic commands ###
