"""add_has_imported_defaults_to_user

Revision ID: 1c57f846940c
Revises: b4a8d43ccfe5
Create Date: 2026-05-04 10:10:27.586982
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1c57f846940c'
down_revision: Union[str, Sequence[str], None] = 'b4a8d43ccfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    if inspector.has_table('adventures'):
        op.drop_table('adventures')
    if inspector.has_table('game_states'):
        op.drop_table('game_states')

    cols = [c['name'] for c in inspector.get_columns('avatars')]
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        if 'adventure_id' in cols:
            batch_op.drop_column('adventure_id')

    cols = [c['name'] for c in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'has_imported_defaults' not in cols:
            batch_op.add_column(sa.Column('has_imported_defaults', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_imported_defaults')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adventure_id', sa.TEXT(), nullable=True))

    op.create_table('game_states',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_debug_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventures',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('game_over_rules', sa.TEXT(), nullable=True),
    sa.Column('rule_enforcement_mode', sa.TEXT(), server_default=sa.text("'strict'"), nullable=False),
    sa.Column('pacing_minutes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('clock_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_image_styles', sa.TEXT(), nullable=True),
    sa.Column('selected_tone', sa.TEXT(), nullable=True),
    sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('creation_status', sa.TEXT(), nullable=True),
    sa.Column('creation_error', sa.TEXT(), nullable=True),
    sa.Column('generate_scene_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('quests', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_npc_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('generate_item_images', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('award_generation_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_awards', sa.INTEGER(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_awards', sa.INTEGER(), server_default=sa.text('8'), nullable=False),
    sa.Column('original_manifest', sa.TEXT(), nullable=True),
    sa.Column('min_scenes', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_scenes', sa.INTEGER(), server_default=sa.text('5'), nullable=False),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
