"""add_game_over_completed_fields

Revision ID: 68636ceb2b38
Revises: 9555cc9d30eb
Create Date: 2026-04-29 08:57:18.322483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '68636ceb2b38'
down_revision: Union[str, Sequence[str], None] = '9555cc9d30eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_note', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_log', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('game_log')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('status_note')
    # ### end Alembic commands ###
