"""Initial Unified Schema

Revision ID: 9ee9f8808ff8
Revises: 
Create Date: 2026-04-23 20:43:47.807866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9ee9f8808ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('encrypted_api_keys', sa.JSON(), nullable=True),
    sa.Column('llm_settings', sa.JSON(), nullable=True),
    sa.Column('t2i_settings', sa.JSON(), nullable=True),
    sa.Column('image_styles_catalog', sa.JSON(), nullable=True),
    sa.Column('tone_catalog', sa.JSON(), nullable=True),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.Column('earned_awards', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adventure_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('context', sa.String(length=2000), nullable=True),
    sa.Column('strict_rules', sa.Boolean(), nullable=False),
    sa.Column('rule_enforcement_mode', sa.String(length=16), nullable=False),
    sa.Column('time_per_turn', sa.Integer(), nullable=False),
    sa.Column('pacing_minutes', sa.Integer(), nullable=False),
    sa.Column('clock_enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_interval', sa.Integer(), nullable=False),
    sa.Column('generate_scene_images', sa.Boolean(), nullable=False),
    sa.Column('generate_npc_images', sa.Boolean(), nullable=False),
    sa.Column('generate_item_images', sa.Boolean(), nullable=False),
    sa.Column('selected_image_styles', sa.JSON(), nullable=True),
    sa.Column('selected_tone', sa.String(length=100), nullable=True),
    sa.Column('game_over_rules', sa.JSON(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('creation_status', sa.String(length=100), nullable=True),
    sa.Column('creation_error', sa.String(length=500), nullable=True),
    sa.Column('original_manifest', sa.JSON(), nullable=True),
    sa.Column('min_scenes', sa.Integer(), nullable=False),
    sa.Column('max_scenes', sa.Integer(), nullable=False),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('award_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_awards', sa.Integer(), nullable=False),
    sa.Column('max_awards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('status_effects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avatars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('status_effects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('current_scene_id', sa.String(length=50), nullable=False),
    sa.Column('spatial_position', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('wearable_slots', sa.JSON(), nullable=True),
    sa.Column('is_in_inventory', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_portable', sa.Boolean(), nullable=False),
    sa.Column('combination_ingredients', sa.JSON(), nullable=True),
    sa.Column('reveals_item_id', sa.String(length=50), nullable=True),
    sa.Column('is_final_state', sa.Boolean(), nullable=False),
    sa.Column('state_comment', sa.String(length=1000), nullable=True),
    sa.Column('npc_type', sa.String(length=50), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mana', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.PrimaryKeyConstraint('id', 'template_id')
    )
    op.create_table('world_exits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('from_scene_id', sa.String(length=50), nullable=False),
    sa.Column('to_scene_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('lock_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('current_scene_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id')
    )
    op.create_table('world_scenes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.PrimaryKeyConstraint('id', 'template_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('avatar_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_id', sa.String(length=36), nullable=True),
    sa.Column('current_scene_id', sa.String(length=100), nullable=False),
    sa.Column('in_game_time', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('entity_states', sa.JSON(), nullable=True),
    sa.Column('exit_states', sa.JSON(), nullable=True),
    sa.Column('discovered_scenes', sa.JSON(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_debug_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['adventure_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_states')
    op.drop_table('chat_messages')
    op.drop_table('game_sessions')
    op.drop_table('world_scenes')
    op.drop_table('world_maps')
    op.drop_table('world_exits')
    op.drop_table('world_entities')
    op.drop_table('avatars')
    op.drop_table('characters')
    op.drop_table('adventure_templates')
    op.drop_table('users')
    # ### end Alembic commands ###
