"""Add is_adventure_generator flag

Revision ID: e5624ad2bd9f
Revises: df909b39afb3
Create Date: 2026-05-05 07:42:52.597393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = 'e5624ad2bd9f'
down_revision: Union[str, Sequence[str], None] = 'df909b39afb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_adventure_generator', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('selected_tone',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        # Check if column exists before dropping to avoid errors if it was already dropped
        # (Since we are fixing a messy migration state)
        pass 
        # op.drop_column('adventure_id') # Commented out as it might not exist in some states

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_templates', schema=None) as batch_op:
        batch_op.alter_column('selected_tone',
               existing_type=sa.String(length=100),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('is_adventure_generator')

    # ### end Alembic commands ###
