import os

path = r'alembic\versions\b2f08f0d7ceb_separate_adventuretemplate_gamesession_.py'
with open(path, 'r') as f:
    lines = f.readlines()

header = []
body = []
footer = []

# Extract header (imports and revision info)
# Extract upgrade function parts
in_upgrade = False
in_batch_alters = False
upgrade_start_idx = -1
batch_alter_start_idx = -1
drop_start_idx = -1

for i, line in enumerate(lines):
    if 'def upgrade() -> None:' in line:
        upgrade_start_idx = i
        in_upgrade = True
    if in_upgrade:
        if '_drop_table_if_exists' in line and '(' in line:
            if drop_start_idx == -1: drop_start_idx = i
        if 'with op.batch_alter_table' in line:
            if batch_alter_start_idx == -1: batch_alter_start_idx = i
            in_batch_alters = True
        if i > upgrade_start_idx and 'def downgrade() -> None:' in line:
            in_upgrade = False
            upgrade_end_idx = i

# Reconstruct upgrade function
# 1. Start of upgrade
# 2. Batch alters (to fix FKs while tables exist)
# 3. Drops (to clean up old tables)
# 4. Creates (to add new tables)

# This is getting complex with line indices. Let's just find the blocks.
content = "".join(lines)
upgrade_body = content.split("def upgrade() -> None:")[1].split("def downgrade() -> None:")[0]

blocks = upgrade_body.split("\n\n")
batch_blocks = [b for b in blocks if "batch_alter_table" in b]
create_blocks = [b for b in blocks if "op.create_table" in b]
drop_blocks = [b for b in blocks if "_drop_table_if_exists" in b]
other_blocks = [b for b in blocks if b not in batch_blocks and b not in create_blocks and b not in drop_blocks and b.strip() != ""]

new_upgrade_body = "\n    # ### commands auto generated by Alembic - please adjust! ###\n\n"
new_upgrade_body += "\n\n".join(batch_blocks) + "\n\n"
new_upgrade_body += "\n\n".join(drop_blocks) + "\n\n"
new_upgrade_body += "\n\n".join(create_blocks) + "\n\n"
new_upgrade_body += "\n\n".join(other_blocks) + "\n"

# Replace the upgrade function in the original content
new_content = content.split("def upgrade() -> None:")[0] + "def upgrade() -> None:" + new_upgrade_body + "def downgrade() -> None:" + content.split("def downgrade() -> None:")[1]

with open(path, 'w') as f:
    f.write(new_content)
print("Migration script reordered successfully.")
